### ISSUE TITLE
Null Reference Error In Beta Installer

### ISSUE THREAD

**Issue by ChobbyCode** [ChobbyCode/MicroMacro#1]
Unhandled exception. System.NullReferenceException: Object reference not set to an instanec of and object.
  at MicroMacroConsole.Program.AddAsSuggestedApp() in E:\source\repos\MicroMacro\MicroMacro\Program.cs:line 88
  at MicroMacroConsole.Program.Main(String[] args) in E:\source\repos\MicroMacro\MicroMacro\Program.cs:line 46

Reason: Occurs due to pre-set location for a file. 

Temporary Fix: Make sure that there is an valid 'E' drive on your computer.

Fix: Will remove pre-set location and make dynamic in full release of 1.2.0

Unable to find exact location in code. Below is a rough guess.
```c#
line 203:
            Console.ReadLine();
            Process.Start(loc + @"\MicroMacro.exe");
        }

```

**Comment by ChobbyCode** [comment]
Exact cause of error found.

Cause of issue is line 68. To fix it, function is temporarily disabled from use.
Also disabled check for .macro extension field to prevent null error. Should be readded for 1.2.1.

```c#
63        public static void AddAsSuggestedApp()
64        {
65            // Adds as a suggested popup for the .macro extension when people click on open with for .macro
66            var Key = Registry.ClassesRoot.OpenSubKey(".macro");
67            var Type = Key.GetValue("");
68            String myExecutable = Assembly.GetEntryAssembly().Location; // <-- *This is the cause of issue* 
69            String command = "\"" + myExecutable + "\"" + " \"%1\"";
70            String keyName = Type + @"\shell\Open\command";
71            using (var key = Registry.ClassesRoot.CreateSubKey(keyName))
72            {
73                key.SetValue("", command);
74            }
75        }
```
